version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "admin-qc"
          ContainerPort: 8048
        PlatformVersion: "LATEST" 
Hooks:
  - BeforeAllowTraffic: "waitForMinutes"
