version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "payment-qc"
          ContainerPort: 8040
        PlatformVersion: "LATEST" 
Hooks:
  - BeforeAllowTraffic: "waitForMinutes"
