version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "store-qc"
          ContainerPort: 8046
Hooks:
  - BeforeAllowTraffic: "waitForMinutes"
